### PR TITLE
[IMP] make example paths match what

### PR DESCRIPTION
**Pull request by hbrunn**
bootstrap_win_dev.vbs installs if called without parameters

### CODE REVIEW

**Comment by hbrunn** [comment]
or should rather https://github.com/Gnucash/gnucash-on-windows/blob/master/bootstrap_win_dev.vbs#L50 be changed?

**Comment by jralls** [comment]
Why do you think the default directory name should be gcdev-maint instead of gcdev?

**Comment by jralls** [comment]
bootstrap_win_dev.vbs should be changed, which I've done.
I pushed a change from the distribution build machine and that accidentally pulled in gcdev-maint.

**Comment by gjanssens** [comment]
John, should custom.sh.sample be reverted then as well ?
It was altered in the same commit where you inadvertently changed gcdev to gcdev-maint.

**Comment by jralls** [comment]
> On May 7, 2015, at 6:05 AM, Geert Janssens <notifications@github.com> wrote:
> 
> John, should custom.sh.sample be reverted then as well ?
> It was altered in the same commit where you inadvertently changed gcdev to gcdev-maint.
> 
> 

Geert,

Yes, done, thanks for noticing that.

ISTM though that it shouldn’t be different in gcdev-maint, either, nor should the README be changed there. Only custom.sh needs to be different, and it’s not under version control.

**Pull request closed without merging**
