### PR TITLE
Update Croatian translation for gnucash-on-windows 

### PR DESCRIPTION
**Pull request by milotype**

### CODE REVIEW

**Comment by jralls** [comment]
You did this before in #38 and it had to be reverted. The v5 and v6 isl files are incompatible and unless we can update inno setup and all of the isl files at once we have to leave everything at v5.

**Comment by milotype** [comment]
@jralls OK, I'm sorry for the noise. I wasn't sure if it is possible ...
So maybe it's a "new feature" issue? (As I'm not a programmer, I don't know how difficult it is to implement it)

**Comment by fellen** [comment]
But the 3. commit is independend from the Inno setup version

**Comment by jralls** [comment]
@fellen, If you say so. I can't read Croatian so I have to assume that it's all about Inno Setup.

@milotype It about we can have Inno Setup V5 or Inno Setup V6. We can't use V5 translations with V6 or vice-versa so before we can switch to V6 we have to get the Latvian and both Chinese translations updated as well as the Croatian. Chinese isn't too much of a problem, there are [contributions](https://jrsoftware.org/files/istrans/) at 6.1, but the Latvian one is stuck on 5.5.

**Comment by fellen** [comment]
> @fellen, If you say so. I can't read Croatian so I have to assume that it's all about Inno Setup.

And I thought, `Update Croatian readme file` is English. ;-)

**Comment by milotype** [comment]
Yes, the 3. commit (change in the README-hr.win32-bin.txt) is independend from the Inno setup version itself ...

**Comment by jralls** [comment]
@fellen, the commit description is English, but the change is Croatian. No telling what @milotype changed.

On his say-so I've cherry-picked the last commit and pushed it.

**Pull request closed without merging**
