### PR TITLE
msys2 repo mirror selection by env var; fix for 797257

### PR DESCRIPTION
**Pull request by diablodale**
Today, the msys2.org domain is down. Leading to unworkable setups, updates, installs, etc.

I request this PR to address two issues:
- ability to change the msys2 mirror used in this bootstrap
- incorporates the fix for 797257

Allowing the mirror to be selected with this param will solve three things:

1. Enables setup/builds when default repos are unavailable
2. Allows integration into CI pipelines that may intentionally use different mirrors.
3. Allows users on different continents to select and use different mirrors. With this PR, I can use the mirror in Austria (I'm in Germany). My setup time is probably 1/3 what it was earlier this week.

Security concerns

- Packages are signed, so that should still be ok.
- Your bootstrap downloads some EXEs directly. I recommend checking hashs of all downloads. [Separately ask me how I use chocolately down these EXEs instead of this bootstrap]

### CODE REVIEW

**Comment by diablodale** [comment]
Also, when the mirror env var is set, I prepend it to the three pacman mirror lists using this code. This is not required for this PR, but it is suggested.

This is code taken from my prelim Windows Dockerfile for builds. Variable substitution will be needed to accommodate the user's selected $target_dir

```powershell
if (! [string]::IsNullOrEmpty($Env:GNC_WINBUILDER_MSYS2_MIRROR)) {
    "Server = $_GNC_WINBUILDER_MSYS2_MIRROR/mingw/i686/`n" + (Get-Content -Path 'C:/gcdev64/msys2/etc/pacman.d/mirrorlist.mingw32' -Raw) | Set-Content -Path 'C:/gcdev64/msys2/etc/pacman.d/mirrorlist.mingw32'
    "Server = $_GNC_WINBUILDER_MSYS2_MIRROR/mingw/x86_64/`n" + (Get-Content -Path 'C:/gcdev64/msys2/etc/pacman.d/mirrorlist.mingw64' -Raw) | Set-Content -Path 'C:/gcdev64/msys2/etc/pacman.d/mirrorlist.mingw64'
    "Server = $_GNC_WINBUILDER_MSYS2_MIRROR/msys/`$arch/`n" + (Get-Content -Path 'C:/gcdev64/msys2/etc/pacman.d/mirrorlist.msys' -Raw) | Set-Content -Path 'C:/gcdev64/msys2/etc/pacman.d/mirrorlist.msys'
}
```

**Comment by diablodale** [comment]
Here is how I use it already. You can see that I define it as *not* having a slash at the end. And how I prepend it to the mirror lists. This is a real-world example of how this PR enables good integration and helps people on different continents (local mirrors) and gets around failed mirrors easily with a single var.

https://github.com/diablodale/gnucash-dev-docker/blob/master/windows.dockerfile

**Comment by jralls** [comment]
I've already pushed the change for [Bug 797257](https://bugs.gnucash.org/show_bug.cgi?id=797257). 

Wouldn't a command-line parameter for the mirror URI be cleaner than an environment variable?

[Choclolatey](https://github.com/chocolatey/chocolatey.org) looks interesting but I think it would add more complexity than is appropriate for the three executables we need. It would be as effective to run GetFileHash on the download and compare the result to the known hash.

**Comment by diablodale** [comment]
A named command line parameter would also work well. If you prefer that, I'll redo the PR code with that as an approach.

You ok with this?
--preferred-mirror https//xyz.com/mydir/msys2mirror

I can also add in the mirrorlist prepending code if you agree that's ok. Its working very well in my testing.

No, I wouldn't recommend chocolately just for hashes. I use choc for automated installs + hashing.

**Comment by jralls** [comment]
Sure, ```$preferred_mirror``` is fine.  Note the underscore instead of the hyphen, powershell converts command-line parameters directly into variables and hyphens aren't legal in variable names.

I just checked and ```8.8.8.8``` now gives the right answer for repo.msys2.org. It should be the default of ```$preferred_mirror```.

Yes, setting the mirror on the mirror lists is where most of the performance advantage from setting a closer mirror will come from.

**Comment by diablodale** [comment]
switched to parameter approach, and fixed hardcoded usage of 'msys' in one place to use $msys2_root instead

**Comment by diablodale** [comment]
Please hold on a merge. I'm seeing some odd behavior with pacman and I want to be sure it isn't this code.

**Comment by diablodale** [comment]
OK. I have no concerns with this PR now.
I isolated the odd behaviors and they are not directly related to this PR.
I did change the method of persisting the preferred mirror so that it will survive and work with an updated mirrorlist package update from the msys2 repo.

**Comment by jralls** [comment]
Oops, you made a merge-loop. You need to rebase locally, resolve the conflicts, and force-push.

**Comment by diablodale** [comment]
That exactly what I did a few days ago and just now with your update today.
No conflicts locally. All good here. Very odd.

**Comment by diablodale** [comment]
Weird. I see the conflict in the guild has you changed. What's weird is that git didn't tell me of the conflict when I did the rebase.
I can fix it. Hang on.

**Comment by diablodale** [comment]
I don't know why github is complaining.
https://github.com/diablodale/gnucash-on-windows/blob/e0ed4ca671eae8577b6724efc5b4f3ce38d5d61c/gnucash.modules#L122
You can see that the hash is correct. It was put they by the rebase. That branch has it right. But for some reason I don't understand that same branch when viewed in this PR is wrong and has the old hash.
Ideas?

**Comment by diablodale** [comment]
weird. I think vscode didn't --force on the push, and that caused the issue.
resolved it.

**Comment by jralls** [comment]
Much better. Would you mind squashing them into a single commit? Makes you look brilliant and the repo's history cleaner.

**Comment by diablodale** [comment]
squashed

**Comment by jralls** [comment]
Thanks.

**Pull request merged**
