### PR TITLE
Adding Croatian data - please review my comments

### PR DESCRIPTION
**Pull request by milotype**

### CODE REVIEW

**Comment by fellen** [comment]
Wow, a full translated Croatian 6.0 file. You should offer it to innosetup, too.

From my understanding then the changes in gnucash-mingw64.iss are not required, but @jralls might know it better. I also did not full understand, which encoding innosetup prefers in 6.0.

**Comment by gjanssens** [comment]
Impressive work!

Inno defaults to UTF-8. If you convert your isl file to that encoding, I believe you should specify a LanguageCodePage of 0.
As for isl versus changes in gnucash-mingw64.iss: Strictly speaking we can have only an isl file with all translations. In that case it would be sufficient to add the language and point the installer at this .isl file from within gnucash-mingw64.iss.

However I consider it better from a maintenance point of view to separate translations for inno strings and gnucash-specific strings. So the isl file should contain only generic translations, that is all strings that come from inno setup itself. The translation section in gnucash-mingw64.iss should only have translations for strings gnucash adds to the installer.

**Comment by fellen** [comment]
@gjanssens Thanks, I believe I understand now the parts. Then we should reduce the number of [CustomMessages] by replacing the following by standard messages;
FullInstall->FullInstallation, 
CustomInstall->CustomInstallation,
CreateDesktopIcon=
RunPrg->LaunchProgram=Launch %1
...more?

**Comment by jralls** [comment]
@gjanssens Not sure which `LanguageCodePage` you're referring to, but for clarity the one in `gnucash-mingw64.iss` applies to `README-hr.win32-bin.txt` and the ones in .isl files apply to that file. 

@milotype if you're planning to submit your 6.0.0 translation to [inno-setup](https://github.com/jrsoftware/issrc/blob/master/CONTRIBUTING.md) they'd probably appreciate it if you transcoded to UTF-8 and change `LanguageCodePage` accordingly as @gjanssens suggests.

**Comment by milotype** [comment]
> Not sure which `LanguageCodePage` you're referring to, but ...
In my "gnucash-mingw64.iss" file I simply added a line with: `hr.LanguageCodePage=0`

> if you're planning to submit your 6.0.0 translation ...
Yes I'm planning to submit the 6.0.0 and see what they say. But I'm unsure about the utf-8 coding. All language files I've checked on their website have a `LanguageCodePage` set. So did the Croatian 5.3.3 file. That's why I tried to follow the present notations for `LanguageCodePage`.
The chinese and latvian files in GnuCash's folder have it as well.
Here are some examples from other languages:
```
LanguageName=Deutsch
LanguageID=$0407
LanguageCodePage=1252
```
```
LanguageName=Portugu<00EA>s (Portugal)
LanguageID=$0816
LanguageCodePage=1252
```
```
LanguageName=Magyar
LanguageID=$040E
LanguageCodePage=1250
```
... but maybe I'm missing the point somewhere ...

**Comment by milotype** [comment]
This is what the specified for translations on their website, both of which I did:
> - Make sure you use the correct LanguageID setting. ...
> - Please use Windows-style line breaks (CR/LF) and not Unix-style line breaks (LF only).
... no mention of utf-8 ...

**Comment by jralls** [comment]
Interesting point. Even the [Dutch translation](https://github.com/jrsoftware/issrc/blob/master/Files/Languages/Dutch.isl) whose last commit is titled "Convert to UTF-8" still has `LanguageCodePage=1252`. I found the answer in this [translation newsgroup article](http://news.jrsoftware.org/read/article.php?id=2521&group=jrsoftware.innosetup.translations#2521): Inno-setup ignores the `LanguageCodePage` and switches to UTF-8 if it finds a BOM. The translations section of [CONTRIBUTING.md](https://github.com/jrsoftware/issrc/blob/master/CONTRIBUTING.md) says that the BOM is required and cautions against using the Github editor.

**Comment by fellen** [comment]
Read http://www.jrsoftware.org/ishelp/index.php?topic=unicode:
 :
Unicode Inno Setup uses the existing ANSI .isl language files and you should not and may not convert these to Unicode or anything similar since it does so automatically during compilation using the LanguageCodePage setting of the language. However, you do need to convert existing [Messages] and [CustomMessages] entries in your .iss files to Unicode if the language used a special LanguageCodePage.
 :

**Comment by milotype** [comment]
@jralls Yes, I've read that too, but didn't figure out, what it effectively means. Thank you for clarifying.
So 2 things can happen now (I think):

1. Can someone commit this PR? My file "gnucash-mingw64.iss" in this PR should be correct.
2. I would make a new PR with the "Croatian-6.0.0.isl" in UTF-8 with BOM

Aggreed?

**Comment by milotype** [comment]
@fellen sorry, just missed your comment ... so, no changes from your point of view?

**Comment by fellen** [comment]
From my understanding the .isl files must stay in ANSI, while the .iss should be in utf8.

**Comment by fellen** [comment]
... at least for already existing files, because later they write "Unicode Inno Setup supports UTF-8 encoded .iss and .isl files (but not UTF-16)."

**Comment by milotype** [comment]
As my "Croatian-6.0.0.isl" is a new file, UTF-8 file should be good then.

Maybe we'll know for sure, if I submit my "Croatian-6.0.0.isl" as UTF-8 file to them and see what their reaction is?

**Comment by fellen** [comment]
They can also have forgotten to update the page, when they dropped the ANSI flavour of the installer, or delayed it.

My suggestion: One with a Windows VM (@gjanssens , @jralls ?) should do test run and if successful, commit this PR.
@milotype Ask the inno setup guys, if above page is still valid or which encoding they prefer for your new file. If they now prefer utf-8 create a new PR after conversion.

**Comment by milotype** [comment]
I've just submitted my file with utf-8, also asking them about the encoding. 
I'll keep you guys posted here!

**Comment by jralls** [comment]
@fellen, your understanding is outdated, as is the Inno-setup documentation: 6.0.0 allows UTF-8 .isl files, see the links posted earlier. However, the "Unicode" they're talking about in that quote is Windows native UTF-16.

That said, there's nothing wrong with @milotype's translation as it stands and I'll merge the PR soon if no one gets to it first.

**Comment by jralls** [comment]
> That said, there's nothing wrong with @milotype's translation

Spoke too soon. Unfortunately it errors out:
```
Error on line 1 in C:\gcdev64\src\gnucash-on-windows.git\inno_setup\Croatian-6.0.0.isl: Text is not inside a section.
```

**Comment by jralls** [comment]
That turns out to be a stray CR (not a Windows CRLF) at the beginning of the file.
There's also an undeleted English string at line 224.

@milotype, I think it's safer if you fix it. Windows is too finicky about code pages for me to be confident that I can get the file saved in the right encoding.

**Comment by milotype** [comment]
@jralls thanks for catching the errors. Line 224 was my mistake, Line 1 of the convertor I used.
Can you check the attached files? Packed are both encoding forms.
[Croatian-6.0.0.zip](https://github.com/Gnucash/gnucash-on-windows/files/3303221/Croatian-6.0.0.zip)

**Comment by milotype** [comment]
Please take my utf-8 file and convert to windows-1250. It seems to me, that I'm not able to save the file in windows-1250 encoding on my mac.

**Comment by jralls** [comment]
Well, a new wrinkle. Setup-mingw64.ps1 installs Inno-setup 5.5.9 and of course it doesn't read the UTF-8 version.

The Greek translation has been booted to "unofficial" but at least it's a 6.0.0 translation. The Latvian and Chinese ones aren't.  I need to change setup-mingw64.ps1 to gracefully upgrade to 6.0.0, but in the meantime I think the safest thing to do for this PR is to use the `Croatian.isl` from the JRSoftware github repo.

I did install Inno-setup-6 on my VM and test the UTF-8 Croatian file: It works fine, so it's safe to submit to JRSoftware.

**Comment by milotype** [comment]
So is there anything I should do now for GnuCash and what will happen with this PR? 
At least commit "gnucash-mingw64.iss" and discard the .isl file?
Should I make a new PR with the original "Croatian-5.5.3.isl"?

**Comment by jralls** [comment]
I made the requisite changes, amended your commit, and pushed the result.  Github doesn't recognize the merge because of the amendment, so closing. Thanks for your work!

**Comment by milotype** [comment]
@fellen @jralls 
Just to inform you that I got a reply for the "Inno Setup" file:

> Thanks for the update, it looks good. UTF8 is indeed ok since version 6.
> Greetings, Martijn

The Croatian 6.0.0 file can now be found at http://www.jrsoftware.org/files/istrans/
So whenever needed, it can be pulled from there.
And thank you again for all your help.

**Comment by jralls** [comment]
Excellent! Thanks for the update.

**Pull request closed without merging**
