### PR TITLE
BugFix action for downloading mingw-get.zip (binary file)

### PR DESCRIPTION
**Pull request by wonhoseo**
1. add sub procedure for downloading when  file type is binary type.
2. In the case downloading mingw-get.zip -> download is ok. but unzip mingw-get.zip is error .
    -> bug fixed

### CODE REVIEW

**Comment by jralls** [comment]
I've never had a problem with downloads in the bootstrap vbs-script.  What problem are you having and exactly how are you invoking the script that causes it?

Something of a separate matter, the mingw.org-based scripts have only a few more months to live: GnuCash 2.8 will use a new mingw-w64 build system.

**Comment by wonhoseo** [comment]
Thanks for your comments.
Windows10. 64bit language korean Env. Asia 
Downloading is no problems. 
Downloaded mingwiget.zip file cannot be unziped.
When manual download file  mingwget.zip is able to unzipped.

Thanks

**Comment by wonhoseo** [comment]
Maybe text file type writing. decoding error. 
And fixed code is more faster than previous code for downloading speed.

**Comment by wonhoseo** [comment]
Thanks for your comments.
Windows10. 64bit language korean Env. Asia 
Downloading is no problems. 
Downloaded mingwiget.zip file cannot be unziped.
When manual download file  mingwget.zip is able to unzipped.

Thanks

**Comment by gjanssens** [comment]
Why did you close this PR if it fixes a real problem for you ?

**Comment by marudesign** [comment]
it's real problems for me. but I can not explain reproduxe steps for others. it's maybe  minor patches. If others did the same problems. it's the helpful solutions.

**Comment by gjanssens** [comment]
My problem is I can't test you patch on my Win XP development box as it seems it won't download from github any more by script. This is not a problem with your PR, because it fails both with our without your changes. I suspect an expired root certificate while the XP box doesn't get updates any more. I should probably decommission it by now... I'll get back to this later on.

**Comment by gjanssens** [comment]
I have tested this on my 'new' Windows 7 test system and your PR works fine so I have chosen to add it. As @jralls already mentioned it will only be useful for the few remaining 2.6.x releases still to come. For 2.8.x the build system was completely rewritten.
Still thanks for submitting your patch!

**Pull request closed without merging**
