### PR TITLE
Update to aqbanking-6.1.3

### PR DESCRIPTION
**Pull request by fellen**
Several fixes on AqHBCI and OFX

### CODE REVIEW

**Comment by fellen** [comment]
@jralls Because of the short remaining time: do you want to include https://www.aquamaniac.de/rdm/projects/aqbanking/repository/revisions/271cbe4ee515fb22797b5180f97db7cc3b1d0b04 or should we ask Martin for another release?

**Comment by jralls** [comment]
@fellen we should ask Martin for another release. One would have thought it obvious to him that OFX doesn't work without the patch and he'd do the release without being asked, but I guess not.

If he doesn't make a new release by Thursday I'll use 6.1.3 with a jhbuild patch for 271cbe4e.

**Comment by fellen** [comment]
I wrote him...

**Comment by fellen** [comment]
And there is 6.1.4

**Comment by fellen** [comment]
A HBCI user reported on gnucash-de he can now the first time
1. access his credit card
2. use an optical TAN.

**Pull request merged**
