### PR TITLE
[FIX] install perl during windows bootstrap

### PR DESCRIPTION
**Pull request by hbrunn**
we need it in functions.sh called by install.sh

### CODE REVIEW

**Comment by jralls** [comment]
True, but historically mingw perl hasn't worked very well. The developers prefer Strawberry Perl.

**Comment by hbrunn** [comment]
I see. But then I'd propose to mention in the readme that you have to install perl before running `install.sh` - If someone starts with a vanilla windows installation like me, she'll get stuck there too

**Comment by jralls** [comment]
Good thought. Done.

**Comment by gjanssens** [comment]
If fact you're both wrong...

1. msys-perl is installed via the inst_msys() function in install_impl.sh. The bootstrap script only installs the bare minimum to get started. From there install.sh (which calls install_impl.sh) takes over.

2. msys-perl is all that is needed to *build* gnucash. That's why there is no mention of installing Strawberry or Active perl in the accompanying readme file. Historically indeed the msys-perl version was too old. I fixed this when I migrated the windows build scripts to their own repository.
Strawberry/Active perl is only needed to fetch quotes while running gnucash.

**Comment by gjanssens** [comment]
Holger, if you get struck while following the instructions, I'd like to know what errors you get exactly. The script as written should install perl so I wonder why that didn't work for you.

**Comment by hbrunn** [comment]
@gjanssens https://github.com/Gnucash/gnucash-on-windows/blob/8fd8089355ea852314be3c2b41ee87a5f01c71e2/install.sh#L103 indirectly calls perl: https://github.com/Gnucash/gnucash-on-windows/blob/82da9e34a7fcdb26266ceb15bb238c658c60334d/functions.sh#L321, and this happens before `inst_msys` is run.

If this shell is close enough to sh, we could replace `get_major_minor` by
```
version=$1
major=${version%%.*}
remainder=${version#$major.}
minor=${remainder%%.*}
remainder=${remainder#$major.$minor}
case $major in
    (*[!0-9]*) major=0 ;;
esac
case $minor in
    (*[!0-9]*) minor=0 ;;
esac
echo $((major * 100 + minor))
```

**Comment by gjanssens** [comment]
Ah, looks like I broke a fresh build myself...

The shell is close enough to bash for your proposal to work. On the other hand I have chosen to delay the gnucash version test instead to the actual call of inst_boost. This has been pushed earlier today.

Thank you for reporting this and offering constructive solutions. That's highly appreciated.

**Pull request closed without merging**
